
#Settings for the normal tier enchanting infuser.
[normalInfuser]

	#Global scale for all enchantment prices. Represents the maximum total cost when the most expensive combination of enchantments for a given item is applied at once.
	#This is not a strict value and may be exceeded, since each applied enchantment level always costs at least one.
	#Range: 1 ~ 5000
	[normalInfuser.costs]
		maximumCost = 100
		#When scaling costs, only account for vanilla enchantments. Otherwise enchanting costs will become ludicrously cheap with many modded enchantments present.
		scaleCostsByVanillaOnly = true

#Settings for the advanced tier enchanting infuser.
[advancedInfuser]

	#Global scale for all enchantment prices. Represents the maximum total cost when the most expensive combination of enchantments for a given item is applied at once.
	#This is not a strict value and may be exceeded, since each applied enchantment level always costs at least one.
	#Range: 1 ~ 5000
	[advancedInfuser.costs]
		maximumCost = 150
		#When scaling costs, only account for vanilla enchantments.
		scaleCostsByVanillaOnly = true
