#!/usr/bin/env python3
"""Trace the FizzleSMP shield (art/shield.png) as a full 256px .glyph — no
medallion frame, just the shield on transparent background. Point-sampled
from the 1024px source with channel-rounded quantization and blue-shift
correction on near-grey pixels.
"""
import os
import struct
import zlib

N = 256
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'shield.png')


def read_png(path):
    """Minimal stdlib-only PNG reader. Returns (w, h, rows of (r,g,b,a))."""
    with open(path, 'rb') as f:
        sig = f.read(8)
        assert sig == b'\x89PNG\r\n\x1a\n'
        ihdr = None
        idat = b''
        while True:
            hdr = f.read(8)
            if len(hdr) < 8:
                break
            length = struct.unpack('>I', hdr[:4])[0]
            ctype = hdr[4:8]
            data = f.read(length)
            f.read(4)
            if ctype == b'IHDR':
                w, h = struct.unpack('>II', data[:8])
                ihdr = (w, h, data[8], data[9])
            elif ctype == b'IDAT':
                idat += data
            elif ctype == b'IEND':
                break
        w, h, bd, ct = ihdr
        raw = zlib.decompress(idat)
        bpp = {2: 3, 6: 4, 0: 1, 4: 2}[ct] * (bd // 8)
        stride = 1 + w * bpp
        pixels = []
        prev_row = b'\x00' * (w * bpp)
        for y in range(h):
            row_data = raw[y * stride: (y + 1) * stride]
            ftype = row_data[0]
            scanline = bytearray(row_data[1:])
            for i in range(len(scanline)):
                a = scanline[i - bpp] if i >= bpp else 0
                b_val = prev_row[i] if y > 0 else 0
                if ftype == 1:
                    scanline[i] = (scanline[i] + a) & 0xff
                elif ftype == 2:
                    scanline[i] = (scanline[i] + b_val) & 0xff
                elif ftype == 3:
                    scanline[i] = (scanline[i] + (a + b_val) // 2) & 0xff
                elif ftype == 4:
                    c = prev_row[i - bpp] if i >= bpp and y > 0 else 0
                    p = a + b_val - c
                    pa, pb, pc = abs(p - a), abs(p - b_val), abs(p - c)
                    pr = a if pa <= pb and pa <= pc else (b_val if pb <= pc else c)
                    scanline[i] = (scanline[i] + pr) & 0xff
            prev_row = bytes(scanline)
            row = []
            for x in range(w):
                off = x * bpp
                if bpp == 4:
                    row.append(tuple(scanline[off:off + 4]))
                elif bpp == 3:
                    row.append((scanline[off], scanline[off + 1], scanline[off + 2], 255))
            pixels.append(row)
        return w, h, pixels


def quantize(r, g, b):
    """Quantize with blue-shift correction and channel rounding."""
    sat = max(r, g, b) - min(r, g, b)
    if sat < 35:
        avg = (r + g + b) // 3
        r, g, b = avg, avg, avg
    def q(v):
        return min(252, round(v / 36) * 36)
    return '#%02x%02x%02x' % (q(r), q(g), q(b))


print(f'Reading {SRC}...')
sw, sh, spx = read_png(SRC)
print(f'  source: {sw}x{sh}')

bw, bh = sw / N, sh / N
flat = {}
for dy in range(N):
    for dx in range(N):
        sx = min(int((dx + 0.5) * bw), sw - 1)
        sy = min(int((dy + 0.5) * bh), sh - 1)
        r, g, b, a = spx[sy][sx]
        if a < 128:
            continue
        flat[(dx, dy)] = quantize(r, g, b)

# ---- emit -------------------------------------------------------------------
pool = "@$%&*+=oOxX0123456789abcdefghijklmnpqrstuvwyzABCDEFGHIJKLMNPQRSTUVWYZ?!~^/<>[]{};:_|`(),-\"\'"
MAX_COLORS = len(pool)

used = []
for y in range(N):
    for x in range(N):
        c = flat.get((x, y))
        if c and c not in used:
            used.append(c)

def _rgb(h):
    h = h.lstrip('#')
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)

while len(used) > MAX_COLORS:
    best_d, best_i, best_j = float('inf'), 0, 1
    for i in range(len(used)):
        ri, gi, bi = _rgb(used[i])
        for j in range(i + 1, len(used)):
            rj, gj, bj = _rgb(used[j])
            d = (ri - rj) ** 2 + (gi - gj) ** 2 + (bi - bj) ** 2
            if d < best_d:
                best_d, best_i, best_j = d, i, j
    victim = used[best_j]
    survivor = used[best_i]
    for k in list(flat.keys()):
        if flat[k] == victim:
            flat[k] = survivor
    used.pop(best_j)

print(f"  palette: {len(used)} colors (pool: {MAX_COLORS})")
ch = {c: pool[i] for i, c in enumerate(used)}

lines = [
    "# FizzleSMP shield — full trace, generated by shield.gen.py",
    "# Point-sampled from art/shield.png (1024px) to 256px.",
    f"size: {N}", "", "legend:", "  . transparent",
]
for c in used:
    lines.append(f"  {ch[c]} {c}")
lines += ["", "frame:"]
for y in range(N):
    lines.append("  " + "".join(ch[flat[(x, y)]] if (x, y) in flat else "." for x in range(N)))

out_path = os.path.join(HERE, "shield.glyph")
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out_path}  ({len(used)} colors, {N}x{N})")
