name = "Fizzle's SMP"
author = "rfizzle"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a474cad5b1ea4c570a873185db51ce5ed290203b9ee9b29d36f2e400171cd226"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "config/paxi/datapacks"
