name = "Fizzle's SMP"
author = "rfizzle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce7b0c73c5b0eadd27704e838fd70a99ffa7e64ecbe8c1b281acad27c11b6d2a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "config/paxi/datapacks"
