name = "Fizzle's SMP"
author = "rfizzle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d13bfe85ac94f7f11b7975760c8e47cf4cd11f6d22470f78ce90fe4c59133a6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "config/paxi/datapacks"
